name: (Job) npm build & optionally upload FE artifact

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      environment:
        required: true
        type: string
      upload:
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: Build & optionally upload FE artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Find node_modules cache
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      # - name: Copy environment variables
      #   run: cp deploy/config/${{ inputs.region }}/.env.${{ inputs.environment }} .env

      - name: Build
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v3
        if: ${{ success() && inputs.upload }}
        with:
          name: build-${{ inputs.region }}-${{ inputs.environment }}
          path: dist
          retention-days: 1
          if-no-files-found: error
